version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    depends_on:
      - cadvisor
      - node_exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
    - prometheus

  cadvisor:
    container_name: cadvisor
    platform: linux/x86_64
    image: gcr.io/cadvisor/cadvisor  # This is an example ARM64-compatible image
    network_mode: "host"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    devices: 
      - "/dev/kmsg"
      
  # cadvisor:
  # image: gcr.io/google-containers/cadvisor:latest   # This is an example ARM64-compatible image
  # ports:
  #     - "8080:8080"
  # volumes:
  #   - /:/rootfs:ro
  #   - /var/run:/var/run:rw
  #   - /sys:/sys:ro
  #   - /var/lib/docker/:/var/lib/docker:ro

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
